### ISSUE TITLE
Update readme to include how to use it

### ISSUE THREAD

**Issue by AmeerMansourGWsp** [ricaun-io/Aps.Sample.App#1]
Hi 
i was trying to make it work with my app and i got some errors. apperciate if you can let me know how to solve it.
first i changed client id and url
![image](https://github.com/user-attachments/assets/dc383c4d-4b89-44a9-82fe-98012a480043)
but i got this error
![image](https://github.com/user-attachments/assets/26643daa-2669-4e9d-a431-ab27a453fcdb)
therefore i added client secrets 
![image](https://github.com/user-attachments/assets/7b02fc3d-f313-4d07-a57a-d5da1b94dab8)
then i got this error which i don't know how to solve it.
![image](https://github.com/user-attachments/assets/44e0b2a1-f721-4993-b6fd-fb43ad7c0ae4)

i really appreciate if you can update readme so it includes how to setup this project to work on other APS Project and illustrate if there are some configurations needed

**Comment by ricaun** [comment]
Hello,

I believe your application type does not support, at least I only tested with PKCE for Desktop. 

When you create the application you can select, the type.

![image](https://github.com/user-attachments/assets/130f87fc-149f-4682-bb04-2ca2dca08f40)

What type is your application? 

Maybe `Traditional Web App` does not support PKCE option😞

**Comment by AmeerMansourGWsp** [comment]
you are absolutly right !
i uses Traditional Web App. i will try that and let you know .
thanks 👍

**Comment by AmeerMansourGWsp** [comment]
thanks it works !
but it has issue the first time of loggin it will ask user to grant permission so it crash after that it will run successfully !
this is the error 
![image](https://github.com/user-attachments/assets/21ba9fbc-9fea-438c-9b5a-d970b87a1896)
that error occurs with GetThreeLeggedTokenAsync function
and after that error i logged in again and it worked but asks for permission first 
![image](https://github.com/user-attachments/assets/29d4d6fb-a745-4968-828f-dbf7cf46ce78)

how to handle such case ?

**Comment by AmeerMansourGWsp** [comment]
I managed to fix it . i think we need to fix navigation to be like this 
![image](https://github.com/user-attachments/assets/7bec8b63-390a-4e86-b500-3227f50318b6)

i will close this issue thanks.

**Comment by ricaun** [comment]
The error kinda make sense, I added the try/catch just to ignore the exception 🙃


> I managed to fix it . i think we need to fix navigation to be like this ![image](https://private-user-images.githubusercontent.com/151910954/351147543-7bec8b63-390a-4e86-b500-3227f50318b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2OTY1OTAsIm5iZiI6MTcyMTY5NjI5MCwicGF0aCI6Ii8xNTE5MTA5NTQvMzUxMTQ3NTQzLTdiZWM4YjYzLTM5MGEtNGU4Ni1iNTAwLTMyMjdmNTAzMThiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QwMDU4MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzkwZDc4YmZkYWMxZmNmMTA0NjY0NmM3ZTFmNDk2MmE2MzFiM2EyNjliZGE5NzNlYmY4MWY5YTUxMDU4YTkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NcNzVUMGqrn6XAfUmQNGbtbNpZUiDX-2vBaoYv-Rk4U)
> 
> i will close this issue thanks.

That's looks better 🤣

If you want to do a PR with that change 🤟🏻

**Comment by ricaun** [comment]
Hello @AmeerMansourGWsp, just to point that I updated the project with some how to use.

I updated the `ApsService` with `ClientId`, `CallbackUrl` and `Scopes` in the constructor. And remove the client_secret to not create confusion.
